### ISSUE TITLE
辞書に候補が重複した行が作られる

### ISSUE THREAD

**Issue by tyru** [tyru/eskk.vim#124]
例： `つかe /使/使/使/使/使/使/使/使/使/使/使/使/使/使/使/`

via <http://twitter.com/#!/thinca/status/133862587040415744>

**Comment by tyru** [comment]
今でも再現可能？ cc:@thinca

**Comment by thinca** [comment]
今辞書を見てみたところ、そういったエントリはありませんでした。直ってるっぽいです。

**Comment by tyru** [comment]
確認ありがとうございます！
