### ISSUE TITLE
補完した候補も自動的に辞書登録したい

### ISSUE THREAD

**Issue by tyru** [tyru/eskk.vim#138]
すでに`g:eskk#register_completed_word`という変数があるのを見て、
そういやこんな要望 @Shougo さんに受けてたなぁと思い出したので。

**Comment by Shougo** [comment]
Vim 7.4.775 により候補が分かるようになったので対応したいです。

**Comment by tyru** [comment]
正直最近の補完関連の仕様にはついて行けてない…ので、期待して待機することにします。お願いします。

**Comment by Shougo** [comment]
了解しました。

**Comment by tyru** [comment]
動作確認しないと…

**Comment by Shougo** [comment]
私は逆に eskk の構造がよく分からないので、チェックよろしくおねがいします。
