### ISSUE TITLE
補完候補が出ている際に促音を入力すると変換が終了する

### ISSUE THREAD

**Issue by thinca** [tyru/eskk.vim#163]
たとえば、「さいじっこう」と言う単語を変換する際、`▽さいじ` の時点で自動補完が起動し、そのあと `kk` を入力すると `▽さいじkk` となりますが、ここで変換が強制的に終了してしまい、`▽さいじk` の部分は確定した文字として残ってしまいます。
続きの `ou` を入力すると `kk` の2つ目の `k` がひらがな入力の一部として認識されていて `kou` になるので、最終的にはひらがなモード(変換ではない)で `▽さいじkこう` となります。

**Comment by thinca** [comment]
最新版の eskk.vim と neocomplete で再現することを確認。

**Comment by Shougo** [comment]
@thinca 私の手元では、確かに補完候補が出てくるんですが eskk の変換が終了しません。
具体的な再現方法を示してください。

**Comment by Shougo** [comment]
Fixed.

**Comment by tyru** [comment]
@Shougo ありがとうございます。
