### ISSUE TITLE
:EskkFixDictionaryで略語モードの候補が消える

### ISSUE THREAD

**Issue by tyru** [tyru/eskk.vim#183]
<https://twitter.com/thinca/status/618313766610997248>

> @tyru :EskkFixDictionary したらこの辺りも消えちゃったんですけど、これってどういう仕様でしたっけ…。  http://embed.gyazo.com/2d2634b8c43bdd9977897987885218e0.png

![](http://embed.gyazo.com/2d2634b8c43bdd9977897987885218e0.png)

**Comment by Shougo** [comment]
:+1:

**Comment by tyru** [comment]
:tada:
