### ISSUE TITLE
読み指定時に CTRL-G によるキャンセルが効かない

### ISSUE THREAD

**Issue by mattn** [tyru/eskk.vim#192]
「流れる」を打とうと「NagaReru」と書くべきところに間違って「NagareRu」と入力してしまい

[](http://go-gyazo.appspot.com/a8eeee2ec117f691.png)

読み指定モードになった際、CTRL-G によるキャンセルが効かない。オリジナルSKKだとこのモードで CTRL-G をタイプすると「ながれる」(だったと思う)に戻ります。

**Comment by tyru** [comment]
多分？修正しました。
`<nowait>`付けた方が良いと思いますが、そっちはデフォルトでやるのは変更が大きそうだったのでまだやってないです。

**Comment by tyru** [comment]
修正したのでクローズします。
lmapでマッピングしているため他にマッピングがないので、`<nowait>`付けてないのに待ちが発生しないようになっています。
(Vim の仕様としてコマンドラインモードのマッピングを見たほうが良いような気もしますが)
