### ISSUE TITLE
if_lua を使うとうまく動かない場合がある

### ISSUE THREAD

**Issue by thinca** [tyru/eskk.vim#194]
Lua での比較はロケールによって挙動が変わるらしい。
https://github.com/macvim-dev/macvim/issues/333
これによって辞書を引くのに if_lua を使っている場合、うまく動かない場合がある。
何かしら対策が必要。

- ロケールをチェックしてうまく動く場合のみ if_lua を使う
  - そもそも正しいチェック方法は?
- if_lua 自体を使わない
- if_lua を使わないようにする設定を追加する

**Comment by tyru** [comment]
バグを見る限り同じ文字数（バイト数？）の時は起きないようになってるみたいなので、文字列の長さが違う時は回避する処理を入れた方が良いかもしれませんね。

**Comment by thinca** [comment]
辞書順に並んでいる単語列を二分探索で探索している部分なので、文字列の長さによってと言うのは難しい予感です。

**Comment by thinca** [comment]
@tyru めっちゃ困ってるので方針だけでも決めたいです。今これのせいで、私の環境だと eskk.vim 自体がまともに使えない状態です。

**Comment by tyru** [comment]
？浴空ぬくふお。な気はかよく

**Comment by tyru** [comment]
すみませんw 誤爆しましたwww

**Comment by thinca** [comment]
誤爆の仕方がすごいw

**Comment by tyru** [comment]
とりあえずこの件に関して自分が考えてる方向性としては

1. 無効にするオプションを追加
2. バグ対応追加

という感じです。
2はどんな対応がいいのかは調査する必要がありそうですが。

**Comment by ichizok** [comment]
処理前後で `os.setlocale()` するとか

```lua
local loc = os.setlocale(nil, "collate")
os.setlocale("C", "collate")
-- 処理
os.setlocale(loc, "collate")
```

**Comment by tyru** [comment]
#196 で対処してもらったので閉じます。
ありがとうございました！

**Comment by Shougo** [comment]
閉じられてなかったので閉じます

**Comment by tyru** [comment]
おうふ…ありがとうございます。
