### ISSUE TITLE
変換モード移行キーを `;` ではなく `Q` にして欲しい (再)

### ISSUE THREAD

**Issue by cmplstofB** [tyru/eskk.vim#198]
#197 を開き直します。何度もすいません。
#39 は再変換という似て非なる操作の議論ですので，[#39 で議論済みという話](https://github.com/tyru/eskk.vim/issues/197/#2 "github/issues") ではありませんでした。
私が望むのは単純に，平仮名モードで `Q` を押下すると変換モードに移行するというものです。
```vim
lnoremap Q <Plug>(eskk:phase:henkan)
```
みたいな割り当てが出来ればよいのですが……。

#197 引用
> [後から▽モードに入る方法 --- SKK Manual](http://www.bookshelf.jp/texi/skk/skk_4.html#SEC24 "bookshelf.jp") によると，平仮名モードの時 `Q` キーで変換モードに移行するというのが SKK の規格のようです。
> 実際 Daredevil SKK や iBus (libskk の `keymap/hiragana.json` で定義) など他の主要な SKK 実装でも `Q` キーで変換モードに移行できます。
> しかし現在の eskk.vim (cid: [0f7c3b4](https://github.com/tyru/eskk.vim/commit/0f7c3b4a74f29377a6ef30e7fd89fb340a352dd3 "0f7c3b4a74f29377a6ef30e7fd89fb340a352dd3")) では `Q` キーでなく `;` キーで変換モードに移行する設定になっているようです。
> 恥かしながら平仮名モードにおけるキー設定がどこでなされているか分からないので，その変更箇所を教えていただくか，標準設定を他の SKK 実装に合わせていただくと助かります。
> よろしくお願いします。

**Comment by Shougo** [comment]
Fixed in #246
