### ISSUE TITLE
Setting up dictionary on neovim/vim

### ISSUE THREAD

**Issue by aignas** [tyru/eskk.vim#211]
I have recently started to learn Japanese and I am a heavy vim user. I really like this plugin, which I discovered accidentally and I can already use this to type in hiragana and katakana. Thanks!

However, I am struggling to find information on how to setup the functionality to use a dictionary. I am happy to create a PR for some English documentation, but would love to know how to get the suggestions for kanji working.

The most recent thing that I have tried:
```
$ sudo pacman -S skk-jisyo
$ docker run -d -p 127.0.0.1:1178:1178 uyorum/skkserv-google
```
And add the following to my neovim `init.vim`:
```
    let g:eskk#dictionary = {'path': "~/.local/share/nvim/skk-jisyo"}

    " Use skkserv-google
    " (https://github.com/uyorum/go-skkserv-google)
    let g:eskk#server = {
    \   'host': '127.0.0.1',
    \   'port': 1178,
    \}
```

Do I understand correctly that the server may not work because I am not using `vim` or `vimproc`? Would there be interest in supporting `neovim`? Am I missing anything obvious? What is the shortcut to trigger the completions?

**Comment by Shougo** [comment]
You need to install to use skk server in eskk

**Comment by tyru** [comment]
@Shougo 

> You need to install vimproc to use skk server in eskk

No. now eskk works without vimproc if `has('channel') == 1`. #199 

@aignas 

It seems your configuration is correct.
Please check:

* `:echo has('channel')` outputs `1` (you need Vim 8.0 later)
* skkserv is running on that host and port

However, you can also use eskk (or most SKK implemention) without skkserv (SKK server).
eskk supports skkserv by connecting to a server with +channel or vimproc.
But you can use local SKK dictionary file(s) as a first choice.

Configuration:

```vim
" User (writable) dictionary
  let g:eskk#dictionary = {
  \   'path': '~/.skkdict/user-dict',
  \   'encoding': 'utf-8',
  \}
" System (readonly) dictionary
  let g:eskk#large_dictionary = {
  \   'path': '~/.skkdict/system-dict',
  \   'encoding': 'euc-jp',
  \}
```

The default paths of above dictionaries are

```vim
let g:eskk#dictionary = {
\ 'path': "~/.skk-jisyo",
\ 'sorted': 0,
\ 'encoding': 'utf-8',
\}

let g:eskk#large_dictionary = {
\ 'path': "/usr/local/share/skk/SKK-JISYO.L",
\ 'sorted': 1,
\ 'encoding': 'euc-jp',
\}
```

If you ran `sudo pacman -S skk-jisyo`, you have already downloaded a system dictionary.
The path seems `/usr/share/skk/SKK-JISYO.L` ? maybe.
https://www.archlinux.org/packages/community/any/skk-jisyo/files/

**Comment by tyru** [comment]
Or you can download a system SKK dictionary here.
http://openlab.ring.gr.jp/skk/wiki/wiki.cgi?page=SKK%BC%AD%BD%F1#p7

P.S. `system dictionary` is a term used by eskk.
Not a common term among SKK implementations.

**Comment by aignas** [comment]
I have tried using vim with the method above, but I am getting
```
Error detected while processing function <SNR>79_sendBuffer:
line    6:
E906: Not an open channel
Press ENTER or type command to continue
```

all the time. Do you have any ideas how I colud start debugging it?

Thanks for the suggestions, I tried updating the system dictionary path as well, but that did not work: I just can't get the results to appear. The way I test it:
- Enter into the skk mode with `<C-j>`
- Type "daigaku"
- Expect the results to appear if I press `<C-x><C-o>`

However, I could get it to work with the thesaurus method, where I convert the dictionary as per instructions on [SO](https://vi.stackexchange.com/questions/8733/can-i-write-japanese-skk-text-in-vim).

**Comment by tyru** [comment]
Hmm, `<SNR>79_sendBuffer` doesn't seem to be eskk's function.
Could you investigate the script file name by executing `:scriptnames` when getting the error?
`:scriptnames` shows the list of script numbers and file paths.
I want to know the file path of the script number (`79` is the script number, but it may change if you installing/removing some plugins)

**Comment by aignas** [comment]
You are correct, the issue was a `vim-markdown-composer`, which I did not have setup correctly on vim.

Thanks for the tip! I'll update this once I have more time to play around setting everything up.

**Comment by Shougo** [comment]
I will add neovim support for it later.

**Comment by Shougo** [comment]
@aignas Please test it.
https://github.com/tyru/eskk.vim/pull/214
