### ISSUE TITLE
neovim + deopleteで補完候補が出ているときに促音を入力すると入力が確定する

### ISSUE THREAD

**Issue by ippachi** [tyru/eskk.vim#222]
https://github.com/tyru/eskk.vim/issues/163
これと同じ現象です
deoplete側の問題だったらすいません

## 最小構成
```
# init.vim

call plug#begin('~/.vim/plugged')
  Plug 'tyru/eskk.vim'
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:deoplete#enable_at_startup = 1
```

```
# skk-jisyo

;; okuri-ari entries.
;; okuri-nasi entries.
さいじっこう /再実行/
```

## スクリーンショット
![eskk](https://user-images.githubusercontent.com/19731661/73252850-c9b80380-41fe-11ea-97d5-1a7f111f9f58.gif)

**Comment by Shougo** [comment]
再現しました。

**Comment by ippachi** [comment]
@Shougo 
素早い対応ありがとうございます。
ただ状況変わらず同じ動作です...

**Comment by Shougo** [comment]
先ほどの修正が無意味だったので revert しました。
これは eskk の内部問題のように見えます。

**Comment by Shougo** [comment]
申し訳ありませんが、eskk の内部構造がかなり複雑なので修正が困難になっています。

**Comment by ippachi** [comment]
参考になるかはわかりませんが、vim8 + neocompleteだと問題ありませんでした。

**Comment by Shougo** [comment]
deoplete だと、Vim8/neovim ともに同じ問題になりますね

**Comment by Shougo** [comment]
Fixed.
