### ISSUE TITLE
Some conversions get reverted on leaving the insert mode

### ISSUE THREAD

**Issue by x-yuri** [tyru/eskk.vim#227]
I might be missing something, but please consider the following steps:

1. Enter insert mode (`a`).
2. Enable `eskk` (`<C-j>`). Actually I'm using `<Leader>j` (`imap <Leader>j <Plug>(eskk:toggle)`), but I don't think that's the problem.
3. Type `;omoshiroi<C-x><C-o>`. At this point it reads: 面白い.
4. Type `desu`.
5. Leave insert mode (`<Esc>`).

I expect to see 面白いです, but instead it reads: おもしろいです. It replaces 面白い with おもしろい on pressing `<Esc>`.

From what I can see it has something to do with having only one match. When there are more matches (like with `a;nihonjin<C-x><C-o>desu<Esc>`), and `d` is pressed, [`pumvisible()` is `1`][1], so `s:handle_popupmenu_keys()` switches it back to normal mode, and it works as expected. But with only one match, `pumvisible()` is `0`, so `s:handle_popupmenu_keys()` doesn't get called. It seems like `eskk` thinks that the user hasn't made his choice, so it reverts to what he originally typed.

[1]: https://github.com/tyru/eskk.vim/blob/a679ddb9d114d83af0fad7902fae0147feafb628/autoload/eskk.vim#L389

**Comment by Shougo** [comment]
I think you should set `set completeopt+=menuone` instead of `set completeopt=menu`(default).

**Comment by x-yuri** [comment]
Awesome, `set completept+=menuone` or `set completeopt-=menu completeopt+=menuone` resolves it for me. Feel free to close the issue if there's nothing to be done about it.

**Comment by Shougo** [comment]
Closed.
