### ISSUE TITLE
「ん あ」等を入力しようとすると間のスペースが消える

### ISSUE THREAD

**Issue by kuuote** [tyru/eskk.vim#238]
# 現象
未確定のローマ字が存在する状態でスペースを入力し、その後に文字を入力したり挿入モードを抜けたりするとスペースが削除されます。

# 再現手順
eskk.vimを有効化した状態で`n a`と入力すると、最後のaを入力した時点でnの後に打ったスペースが削除され「んあ」と入力されます

# 構成
Vim 8.2.1603
eskk.vim https://github.com/tyru/eskk.vim/commit/1db7aceb2faf48b791bb4dbb31a34940e1967afe

**Comment by Shougo** [comment]
Slack に記述している調査結果も issue に書き出してください。

**Comment by kuuote** [comment]
すみません。
中途半端にローマ字が入力された状態でマッチしない物(今回はスペース)が入力されると、`autoload/eskk.vim`の`s:filter_rom_no_match`が呼ばれますが、本来であれば https://github.com/tyru/eskk.vim/blob/1db7aceb2faf48b791bb4dbb31a34940e1967afe/autoload/eskk.vim#L1160 に到達するべき所ができていないのが原因だと思われます。

**Comment by kuuote** [comment]
とりあえずmsimeの分岐内の処理を`handle \`char\``の後の`if map isnot NO_MAP`の直後にコピーしたら望んだ挙動をするようですが、これで正しいのかは分からないです。
