### ISSUE TITLE
--INSERT (eskk)-- makes more sense than --INSERT (lang)--

### ISSUE THREAD

**Issue by x-yuri** [tyru/eskk.vim#239]
When you enable a keymap, its name is usually displayed in the insert mode indicator. E.g. after `:setlocal keymap=kana<CR>a` the indicator is `--INSERT (kana)--`. `eskk` makes it look like it enables some sort of a keymap. But since `'keymap'` option doesn't get changed, the indicator is `--INSERT (lang)--`. The value for the indicator is taken from (in the order of precedence) `b:keymap_name` variable, `'keymap'` option, or falls back to ["lang"][1]:

> When set to 1, the value of the "b:keymap_name" variable, the 'keymap' option or "<lang>" appears in the status line.

The idea behind `b:keymap_name` variable is to provide a shorter name if keymap filename is too [verbose][2]:

> The "b:keymap_name" can be set to a short name, which will be shown in the
status line.  The idea is that this takes less room than the value of
'keymap', which might be long to distinguish between different languages,
keyboards and encodings.

A good place to set `b:keymap_name` would be after the [following block][3]. What do you say? Should I create a PR?

[1]: https://neovim.io/doc/user/insert.html#i_CTRL-^
[2]: https://neovim.io/doc/user/mbyte.html#mbyte-keymap
[3]: https://github.com/tyru/eskk.vim/blob/1db7aceb2faf48b791bb4dbb31a34940e1967afe/autoload/eskk.vim#L1822-L1833

**Comment by Shougo** [comment]
Please create the PR.  I will test it.
