### ISSUE TITLE
辞書登録モードでの漢字変換で候補一覧が出ない

### ISSUE THREAD

**Issue by TaroYamasaki** [tyru/eskk.vim#245]
eskkで漢字変換を行なった際、辞書登録を促されたので一文字ずつ変換しながらミニバッファに入力していこうとしました。このとき、スペースキーを連打すると一覧表示されるはずの候補が一瞬で消えてしまい、選択することが出来ませんでした。
辞書登録の際にも漢字変換が問題なく使えた方が便利に思います。
ちなみに、このとき使用していた環境の詳細は以下の通りです。

vim(windows用のバイナリ)

	VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 24 2020 11:05:54)
	MS-Windows 64 ビット GUI/コンソール 版
	適用済パッチ: 1-1287
	Modified by koron.kaoriya@gmail.com
	Compiled by koron.kaoriya@gmail.com
	Huge 版 with GUI.  機能の一覧 有効(+)/無効(-)

OS

	Microsoft Windows [Version 10.0.18363.1256]

数回ほど同じ操作を繰り返しましたが、この問題はその度に再現しました。

**Comment by Shougo** [comment]
手元で再現しません。もっと具体的に手順の説明をおねがいします。
我々にはエスパー能力がありません。

あと、できれば最小構成の設定をお願いします。
設定に依存する可能性があるので

**Comment by Shougo** [comment]
https://github.com/tyru/eskk.vim/issues/238

こちらも厳密にはまだ不十分なのですがより優れた再現手順です。

**Comment by TaroYamasaki** [comment]
迅速な返信をありがとうございます。おっしゃる通りです。すみませんでした。

問題の再現手順を以下に示させていただきます。

「邪知暴虐」(初めて入力・変換する辞書にない単語であれば何でもいいです。)
と入力し、変換しようとすると、
画面最下部のプロンプト(ミニバッファと言いましたが、誤記です。申し訳ありません。)
にて辞書登録が促されました。そこで辞書登録のために「邪」「知」「暴」「虐」を一文字ずつ変換しようと
したのです。そして、二文字目の「知」で、スペースキーを数度叩いて、本来なら
変換候補が一覧表示されるところで、件の問題が発現しました。
一瞬だけ候補の一覧が表示された後、一覧が表示される前の最後の候補
(私の場合は「地」でした)が表示されたまま、いくらスペースを叩いても
動かなくなったのです。

以下、最小構成です。

call plug#begin('~/.vim/plugged')
Plug 'tyru/eskk.vim'
call plug#end()

let g:eskk#large_dictionary = {
			\	'path': "C:/Users/UserName/AppData/Roaming/skk-cli/SKK-JISYO.L",
			\	'sorted': 0,
			\	'encoding': 'utf-8',
			\}


" 日本語で入力を開始できるようにする。
nmap ii i<c-j>
nmap aa a<c-j>
nmap oo o<c-j>

nmap ss s<c-j>
nmap II I<c-j>
nmap AA A<c-j>
nmap OO O<c-j>

" バグ対策 置換でもeskkを使えるようにした。その代わり、カウントが動作しなくなったけど……
nnoremap RR R<c-o>:call eskk#toggle()<CR>
nnoremap gRR gR<c-o>:call eskk#toggle()<CR>

nmap SS S<c-j>

" 入力モードを脱出
inoremap jj <Esc>

**Comment by TaroYamasaki** [comment]
追記します。
入力モードには前述のiiで入りました。

**Comment by TaroYamasaki** [comment]
先ほど改めて確認したところ、問題が再現しなくなってしまいました。

**Comment by Shougo** [comment]
最小構成を作り、上記の手順通りにやりましたが再現しません

もうしわけありませんが閉じます

**Comment by TaroYamasaki** [comment]
了解です。
ありがとうございました。
