### ISSUE TITLE
スペースキーをstickyとして使用する（SandS）ようにできますか？

### ISSUE THREAD

**Issue by woodyZootopia** [tyru/eskk.vim#247]
こんにちは．
eskk.vimでは標準だと;キーが変換モード開始のキーとなっていると思うのですが，これをスペースキーに変えることは可能でしょうか？
ドキュメントに倣って
```
autocmd User eskk-enable-post call s:eskk_enable_post()
function! s:eskk_enable_post()
    EskkUnmap -type=sticky ;
    EskkMap -type=sticky "<Space>"
endfunction
```
という設定を試してみたのですが，うまく行きませんでした．

**Comment by Shougo** [comment]
対応させました

```vim
EskkMap -type=sticky <Space>
```

を使用してください

`<Space>` を Sticky Key として使えるようにするのはよいですが、その場合 `<Space>` で変換が行えなくなります。なので、変換モードでは効かなくしました。
真のSandSはできません。

No magic.

**Comment by woodyZootopia** [comment]
素早くご対応いただき，大変ありがとうございます．了解いたしました！

> その場合 <Space> で変換が行えなくなります

確かにそのとおりですね……．キーマッピングの検討が甘かったです，失礼いたしました．
