### ISSUE TITLE
Can't type 出発

### ISSUE THREAD

**Issue by kuator** [tyru/eskk.vim#250]
Hi, I'm a beginner in japanese, thank you for creating such amazing plugin!
My problem:
![Peek 2021-07-20 16-57](https://user-images.githubusercontent.com/25168308/126312884-f8a39f22-be38-48be-9fcb-3064721b39c7.gif)
As you can see, it inserts `しゅpぱつ` instead of `しゅっぱつ`

**Comment by Shougo** [comment]
It is the conflict with auto completion plugin.
Unfortunately, most of auto complete plugins does not support eskk behavior.

deoplete supports it.  I recommend to use it for you instead.
https://github.com/Shougo/deoplete.nvim

**Comment by kuator** [comment]
Thank you for the response. Just wanted to clarify, so I cannot type `出発` with eskk.vim alone? I have to install deoplete.nvim?

**Comment by Shougo** [comment]
You can use eskk.vim without auto completion plugin.
But it conflicts with your auto completion plugin.

**Comment by kuator** [comment]
Thank you, removed it, and now it works!
