### ISSUE TITLE
ライセンスの決定

### ISSUE THREAD

**Issue by thinca** [tyru/eskk.vim#29]
現在helpにはNEW BSD LICENSEと書いてあるが、これは仮なので、後で決定する必要がある。

**Comment by tyru** [comment]
これってなんで仮なんでしたっけ。
正直自分のプラグインではNEW BSD LICENSE使ってるのでそれでいいかなと思ってます。

**Comment by thinca** [comment]
なんかもう NEW BSD LICENSE でいい気がしてきた。色々いまさらだし。

**Comment by tyru** [comment]
:+1:
close ok?

**Comment by thinca** [comment]
:ok:
